services:
  - type: web
    name: tg-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8617104939:AAFVn71gU6WdKPwSeEGOnxiy1j7_r2dKm4k
      - key: ADMIN_IDS
        value: "8361641777"
      - key: TARGET_BOT
        value: "@FunAuthBot"
      - key: API_ID
        value: "37635168"
      - key: API_HASH
        value: 47e36b7f99b31f55be222b4200ea94ca
      - key: SESSION_STRING
        value: BQI-RGAATWam7mmua4XLiKB8DH5JnvSYYSZV5sQYxZEKd2dU6J-Ozt6OqKc5dn3TnnqSe9ZBjaN-2sPSmbBSx5CQasA3-oDwhurBUfIK8nHKDqOymqptViFhMuSnZT0kNK6t6ti9L3KJPElwd4baYnjduB8Dgnea8fNGDseA1bXhkIZdbq2ffGLGS8EXRhMfAPkM0KXk_MQasZNcUQ_ZHUPHitr4pEgJtnfgl8tWjHOl4zKPUqS2SPLtHlSKMigAyscB-a5iBKxdmuS0RaU89AVOcjT_yj6GOUezcMfkCfz88i2WHo9b8-feZyNvo0nTaEc3qRSkyhBYQ-21kQmb3-6CAa05WAAAAAH3bW-aAA
